name: rsp
channels:
  - potassco
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2019.11.27=0
  - cairo==1.14.12
  - certifi=2019.11.28
  - clingo==5.4.0
  - clingo-dl=1.1.0
  - icu==58.2
  - libpng==1.6.37
  - openssl=1.1.1
  - pip=19.3.1
  - pixman==0.38.0
  - setuptools=42.0.2
  - sqlite==3.30.1
  - wheel==0.33.6
  - zlib==1.2.11
  - pip:
      - atomicwrites==1.3.0
      - attrs==19.3.0
      - cairocffi==1.1.0
      - cairosvg==2.4.2
      - cffi==1.13.2
      - chardet==3.0.4
      - click==7.0
      - cloudpickle==1.2.2
      - colorama==0.4.3
      - crowdai-api==0.1.22
      - cssselect2==0.2.2
      - cycler==0.10.0
      - defusedxml==0.6.0
      - entrypoints==0.3
      - eradicate==1.0
      - filelock==3.0.12
      - flake8==3.7.9
      - flake8-eradicate==0.2.3
      - flake8-bugbear
      # TODO we should pin to FLATland version
      - git+https://gitlab.aicrowd.com/flatland/flatland.git@master#egg=flatland-rl
      - future==0.18.2
      - gym==0.14.0
      - idna==2.8
      - importlib-metadata==1.3.0
      - importlib-resources==1.0.2
      - kiwisolver==1.1.0
      - lxml==4.4.2
      - matplotlib==3.1.2
      - mccabe==0.6.1
      - more-itertools==8.0.2
      - msgpack==0.6.2
      - msgpack-numpy==0.4.4.3
      - numpy==1.17.4
      - networkx==2.4
      - ortools==7.4.7247
      - overrides==2.5
      - packaging==19.2
      - pandas==0.25.3
      - pillow==6.2.1
      - pluggy==0.13.1
      - protobuf==3.11.1
      - py==1.8.0
      - pyyaml==5.3
      - pyarrow==0.15.1
      - pycodestyle==2.5.0
      - pycparser==2.19
      - pyflakes==2.1.1
      - pyglet==1.3.2
      - pyparsing==2.4.5
      - pyqt5==5.13.2
      - pyqt5-sip==12.7.0
      - pytest==5.3.1
      - pytest-runner==5.2
      - python-dateutil==2.8.1
      - python-gitlab==1.14.0
      - pytz==2019.3
      - recordtype==1.3
      - redis==3.3.11
      - requests==2.22.0
      - rsp==0.0.1
      - scipy==1.3.3
      - six==1.13.0
      - svgutils==0.3.1
      - timeout-decorator==0.4.1
      - tinycss2==1.0.2
      - toml==0.10.0
      - tox==3.14.2
      - urllib3==1.25.7
      - ushlex==0.99.1
      - virtualenv==16.7.8
      - wcwidth==0.1.7
      - webencodings==0.5.1
      - xarray==0.14.1
      - zipp==0.6.0
